// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ShopASPNETCore.Data;

#nullable disable

namespace ShopASPNETCore.Migrations
{
    [DbContext(typeof(AppDBContent))]
    [Migration("20220830101758_delListIdInTask")]
    partial class delListIdInTask
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "6.0.8");

            modelBuilder.Entity("ShopASPNETCore.Data.Models.Task", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Checked")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("DeadlineDate")
                        .HasColumnType("TEXT");

                    b.Property<int?>("TasksListId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Text")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("TasksListId");

                    b.ToTable("Task");
                });

            modelBuilder.Entity("ShopASPNETCore.Data.Models.TasksList", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ListName")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("TaskList");
                });

            modelBuilder.Entity("ShopASPNETCore.Data.Models.Task", b =>
                {
                    b.HasOne("ShopASPNETCore.Data.Models.TasksList", "TasksList")
                        .WithMany("Tasks")
                        .HasForeignKey("TasksListId");

                    b.Navigation("TasksList");
                });

            modelBuilder.Entity("ShopASPNETCore.Data.Models.TasksList", b =>
                {
                    b.Navigation("Tasks");
                });
#pragma warning restore 612, 618
        }
    }
}
